### PR TITLE
reverseArray_program

### PR DESCRIPTION
**Pull request by thakurrohithsingh**

### CODE REVIEW

**Comment by thakurrohithsingh** [comment]
what happened, sir??

**Comment by Abhivardhan** [comment]
question was to reverse an array, not a string

**Comment by Abhivardhan** [comment]
either update the code by night or this PR will be closed

**Comment by thakurrohithsingh** [comment]
What happened to my code??

**Comment by thakurrohithsingh** [comment]
what should I do Now ??

**Comment by Abhivardhan** [comment]
Opened the PR make the changes required.

**Pull request closed without merging**
